spring:
  application:
    name: Project Roadmap
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8081
  
gitlab:
    api:
      hostUrl: http://192.168.1.178
      privateToken: Yvg1eSzuv3x-AcvFk43V

logging:
  level:
    root: info
